### ISSUE TITLE
DateTime Issue

### ISSUE THREAD

**Issue by bdgjope** [hougaard/ToolBox-Issues#1]
Hi

I had some issues with my code to get offset from UTC when´my code ran on Saas, it's working on my container. So I thought that I would make some tests with the Toolbox. So this is a very simple/stupid code so far. But when I ran it I got this error;

![bild](https://user-images.githubusercontent.com/58292875/186901069-d5696797-f82d-4717-ba38-3f39515264bc.png)

I can't see anything wrong with the code. If I skip the last line it works so the problem lies with that. Am I doing something wrong?

**Comment by hougaard** [comment]
That's a bug, we'll fix that, stay tuned.

**Comment by hougaard** [comment]
<img width="806" alt="image" src="https://user-images.githubusercontent.com/3357237/186931260-f535d2d3-4947-4baf-b971-c9803f6dae9f.png">

Fixed, will deploy to appsource validation Monday.
