### ISSUE TITLE
Type Mismatch

### ISSUE THREAD

**Issue by bdgjope** [hougaard/ToolBox-Issues#10]
Hi
Are we not suppose to be able to use non text values as parameters in text strings when we are using strsubstno?

This works:
var
    Item: record Item;
begin
    Item.setrange("Price Includes VAT",false);
    Message('Not Including VAT: %1. ',Item.count()));
end;

This does not work:
var
    Item: record Item;
    txt: Text;
begin
    Item.setrange("Price Includes VAT",false);
    txt := strsubstno('Not Including VAT: %1. ',Item.count());
    Message(txt);
end;

It gives a runtime error. Of course easily remedied with format. But since it works in standard al i was wondering. And yes, I intend to add additional text before the message

**Comment by hougaard** [comment]
It's one of those annoying joker-based functions.... Fixed in the next version.

<img width="1036" alt="image" src="https://user-images.githubusercontent.com/3357237/229377296-ad7f608f-9d29-402c-822a-ba49654bf923.png">
