### ISSUE TITLE
Will you add support for if evaluate then?

### ISSUE THREAD

**Issue by bdgjope** [hougaard/ToolBox-Issues#11]
Hi
I noticed that Evaluate works even if it´s not on the supported functions web page. However if I try to use if Evaluate then I get this error:
![image](https://user-images.githubusercontent.com/58292875/220561573-5b2fd64c-e454-4616-91f7-77d1398363fe.png)

 I was wondering if you are going to add support for if evaluate then?
 
 And you might wanna update that web page with evaluate and record.copy and whatever other changes you have made

**Comment by hougaard** [comment]
Fixed in the next version.
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/3357237/229370316-edfdb1d9-9e9b-45e2-b48e-1093c0c0cfdf.png">
