### ISSUE TITLE
Format on Date, formats the whole table

### ISSUE THREAD

**Issue by bdgjope** [hougaard/ToolBox-Issues#12]
Hi

I noticed this little peculiarity:

![image](https://user-images.githubusercontent.com/58292875/229050631-e4558291-96a4-4687-a9dc-7a875937a11b.png)

Can you fix this? Thanks

**Comment by hougaard** [comment]
Fixed in the next version, thanks for noticing this.
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/3357237/229366996-51e49ad7-a873-4b90-b07b-1dc24048d8f4.png">
