### ISSUE TITLE
Minor typo in error message

### ISSUE THREAD

**Issue by otherjoel** [hougaard/ToolBox-Issues#19]
Errors say “ex*cep*ting”, should probably say “ex**pec**ting”

![Error messages screenshot](https://github.com/hougaard/ToolBox-Issues/assets/1553115/9a40fdf3-cec3-493a-8fdc-c7a9d85c1e79)

**Comment by hougaard** [comment]
Good catch :)

**Comment by hougaard** [comment]
Fixed in the next build.

**Comment by hougaard** [comment]
update in appsource
