### ISSUE TITLE
String Text Functions (DELCHR Not Supported?)

### ISSUE THREAD

**Issue by steveflorko** [hougaard/ToolBox-Issues#2]
It seems like DELCHR string function is not supported however does appear in the intellisense

Runtime Runtime Error (Line 13): Unknown identifier delchr

![image](https://user-images.githubusercontent.com/95696945/187208020-db5b086a-ac31-42ac-af4f-2e86015abcb3.png)

**Comment by hougaard** [comment]
Good find, DELCHR is one of the functions I never use personally, will add it!

**Comment by steveflorko** [comment]
Thanks,  its a great function in a data clean up type event.

**Comment by steveflorko** [comment]
Oh gosh, wish i would have asked, but   strsubstno    same error.    I can restructure the code to handle this, but would be nice.

![image](https://user-images.githubusercontent.com/95696945/187802201-beeb26c6-ba96-4322-bbcf-4993f9589be8.png)

**Comment by steveflorko** [comment]
and   maxstrlen

![image](https://user-images.githubusercontent.com/95696945/187802700-ddefc155-764d-446b-be52-95755dbe44c6.png)

**Comment by hougaard** [comment]
strsubstno and maxstrlen are now added (version 1.0.0.164)
