### ISSUE TITLE
Release for Version 23

### ISSUE THREAD

**Issue by AvrilHowes** [hougaard/ToolBox-Issues#23]
Trying to install on version 23.0 - get the following error:

You tried to invoke the CodeUnit object with the ID 70310409 from the object Eriks ToolBox Hgd. An object with that ID does not exist in the current application compiled with emit version 23030.

**Comment by hougaard** [comment]
On-prem installation?

Have you installed the AL Compiler & Interpreter app first?

**Comment by AvrilHowes** [comment]
On-prem - YES
Both components are installed: 
Sorry slightly wrong message - they seem to install fine, but when I go to 'Erik's toolbox' from the Tell Me box, the error pops up.

**Comment by AvrilHowes** [comment]
Also if I go to the object list, the Toolbox object range does not appear.

**Comment by hougaard** [comment]
Hmm... The error is saying that the "AL Compiler & Interpreter" app is not there?

Do you have the license added to your FLF file?

**Comment by AvrilHowes** [comment]
Yes I have double checked the licence.  Attached is a licence file export from tenant, and detailed licence file text. It shows the range 703010400-70310499 included, which seems to cover the codeunit in question.

[license.txt](https://github.com/hougaard/ToolBox-Issues/files/12929029/license.txt)
[Braintree BC23 On-Prem 20231012 - no LS and PV Detailed (002).txt](https://github.com/hougaard/ToolBox-Issues/files/12929033/Braintree.BC23.On-Prem.20231012.-.no.LS.and.PV.Detailed.002.txt)

**Comment by hougaard** [comment]
Gonna do a presentation at Summit in Charlotte right now (this message is actually visible on the projector), will check later...

**Comment by hougaard** [comment]
Are the apps installed with the same -scope parameter value?

**Comment by AvrilHowes** [comment]
yes

**Comment by hougaard** [comment]
Very weird, I have just sent a request to Microsoft to see if they have an idea what's going on?

Have you tried to unpublish and republish the apps?

**Comment by AvrilHowes** [comment]
Several times. I am wondering if it is perhaps a MS licence issue. They sometimes have glitches with very new major releases. I will try configuring a new licence.  
I am installing version 1.0.0.226. It does give me warnings about the build when I publish - can I assume that there is not yet a specific build for BC version 23?

**Comment by AvrilHowes** [comment]
I have configured a new licence, loaded it, unpublished the apps, republished and installed. Still getting the error.

**Comment by hougaard** [comment]
Ahhh.. now I know what's going on, you're trying to add the bc22 _runtime_ apps to 23. Not sure why the BC23 apps were not uploaded, I'll get fixed right now ...

**Comment by hougaard** [comment]
https://github.com/hougaard/ToolBox-Issues/releases/tag/v1.0.0.226

**Comment by AvrilHowes** [comment]
Success! 👍 I am up and running on BC 23.  
Love your work!
