### ISSUE TITLE
Azure Sync failed: Could not create container toolboxprograms. Response Code: 409 The specified container already exists.

### ISSUE THREAD

**Issue by ewaldventer** [hougaard/ToolBox-Issues#24]
Add Azure Storage Account and Storage Key.

When saving new programs, it fails with "Azure Sync failed: Could not create container toolboxprograms"

![image](https://github.com/hougaard/ToolBox-Issues/assets/8598877/418de04c-c9e7-4b5a-bee9-df59107bda8a)

I can delete the toolboxprograms, and it gets recreated on the save of the program, but no content and same error as before.

**Comment by hougaard** [comment]
Hmm... Maybe Microsoft changed something in the Azure Blob Storage support. What version of BC is this on?

**Comment by ewaldventer** [comment]
This is BC22.2 OnPrem

**Comment by ewaldventer** [comment]
https://github.com/hougaard/ToolBox-Issues/assets/8598877/87182beb-688d-4360-87a8-89457627e6e9

1. Opened toolbox
2. Deleted container, get message that it is being deleted - no problem.
3. Open toolbox after couple of seconds

**Comment by hougaard** [comment]
I have a fix for this, update is running....

**Comment by hougaard** [comment]
https://github.com/hougaard/ToolBox-Issues/releases/tag/v1.0.0.229
