### ISSUE TITLE
Registration - Multiple Environments

### ISSUE THREAD

**Issue by ewaldventer** [hougaard/ToolBox-Issues#25]
If I'm not mistaken, we should be able to register this on multiple environments?

Went well and is working perfectly on the first one, but on the second environment getting the below error when entering the registration key:
![image](https://github.com/hougaard/ToolBox-Issues/assets/8598877/2cbb2050-0f36-4cbe-960e-60addd2d67a0)

**Comment by hougaard** [comment]
Please email support@Hougaard.com so we can check your license.
