### ISSUE TITLE
Load from Azure Blob Storage fails

### ISSUE THREAD

**Issue by ewaldventer** [hougaard/ToolBox-Issues#26]
Hi,

Saving to Blob Storage now works (#24 )

However loading (**Azure Sync** function) fails with:
![image](https://github.com/hougaard/ToolBox-Issues/assets/8598877/2325ad4d-e4d6-4bf6-863d-54e425c6ce39)

**Comment by hougaard** [comment]
I need the "copy details" to find this, can't reproduce it?

**Comment by ewaldventer** [comment]
If requesting support, please provide the following details to help troubleshooting:

Invalid format of GUID string. The correct format of the GUID string is: CDEF7890-ABCD-0123-1234-567890ABCDEF where 0-9, A-F symbolizes hexadecimal digits.

Internal session ID: 
ae8be1f9-ce12-43b7-bcc4-d00df1d4cc05

Application Insights session ID: 
0c02fbdb-5eb1-47c6-a071-fa5ff861b799

Client activity id: 
70cf938f-c70b-6149-a37c-4e2ae59439bf

Time stamp on error: 
2023-10-26T06:14:51.6220306Z

User telemetry id: 
c75db25b-ac73-42cd-8aef-65cea88fc747

AL call stack: 
"Program Sync Hgd"(CodeUnit 70310420).GetListOfBlob line 33 - ToolBox by Hougaard
"Program Sync Hgd"(CodeUnit 70310420).Sync line 29 - ToolBox by Hougaard
"Program List Hgd"(Page 70310423)."Sync - OnAction"(Trigger) line 9 - ToolBox by Hougaard
"Eriks ToolBox Hgd"(Page 70310420)."Load - OnAction"(Trigger) line 6 - ToolBox by Hougaard

**Comment by hougaard** [comment]
Thanks, seems that your TenantId is either a guid or "common" ... Do you know what it is?

**Comment by ewaldventer** [comment]
These are all On-Prem installations.

**Comment by hougaard** [comment]
Version 1.0.0.232 is uploaded, please try that one.

**Comment by ewaldventer** [comment]
Working, perfectly now. Thank you!
