### ISSUE TITLE
Data inspector - modifying fields that have property editable = false

### ISSUE THREAD

**Issue by GhOnBc** [hougaard/ToolBox-Issues#5]
Hi,

when we run the data inspector and try to modify a field that has editable = false, we get the error:
you do not have access to perform write operations on TABLENAME.

if we then execute some code on that table with the ToolBox, we get the question.
A program is requesting permission to modify data in TABLENAME. 
If we allow this, from then on we are able to also change the field trough the data inspector.

Is it possible to enable modifying these types of field trough the data inspector without having the need to trigger the permissions trough the ToolBox.

kr,

**Comment by GhOnBc** [comment]
Hi,

friendly reminder

**Comment by hougaard** [comment]
Can you verify that the user in question has GodMode access level in the ToolBox (user setup)?

**Comment by hougaard** [comment]
OK, there's a bug (and a way to get around it), I'll fix it for the next version.

If you run any piece of code (message('hello world'); is enough) in the toolbox and then open the object inspector from the toolbox page, then you can edit protected tables.

**Comment by hougaard** [comment]
Fixed in version 1.0.0.176

**Comment by GhOnBc** [comment]
Could you provide a release for on-prem? (min BC19.2) : ) thanks

**Comment by hougaard** [comment]
They're running right now.. The slowest part of the release process...

**Comment by hougaard** [comment]
Release uploaded!
