### ISSUE TITLE
Error Modifying Record

### ISSUE THREAD

**Issue by bdgjope** [hougaard/ToolBox-Issues#6]
Hi

I was trying to modify some records on an OnPrem Installation. Toolbox version is 1.0.0.178. I tried the following

1. Assign Record first. I got this error:
![bild](https://user-images.githubusercontent.com/58292875/211348332-6d20988d-4bd6-4126-93fb-e9b387b665ca.png)

2. TransferFields, apparently not supported (yet?). Got "Unknown member transferfields".

3. Get Records first, with the following error:
![bild](https://user-images.githubusercontent.com/58292875/211348909-2b0ed097-26a5-4014-a52a-45bb14e19be4.png)

4. I decided the the Validation code was not absolutely necessary so used ModifyAll instead. That worked with this code:
![bild](https://user-images.githubusercontent.com/58292875/211349279-efa031c9-3063-427f-9629-6606e8ab7087.png)

Thanks

**Comment by hougaard** [comment]
Rec := Rec doesn't work, but Rec.Copy(fromRec) does in 1.0.0.178.

What is the primary key of the "LSC Periodic Discount" table, the .Get() command in your second screenshot seems to indicate that the first field is a boolean?

**Comment by bdgjope** [comment]
With Rec.Copy(fromRec) I get the same error as with my Get Command. I double checked the Primary Key now and it is a Code field
![image](https://user-images.githubusercontent.com/58292875/211483098-62d7ae0b-66f3-491b-8ca1-4a7d7ef5c30f.png)

**Comment by hougaard** [comment]
Hang on, aren't you missing () on PerDisc.next?

**Comment by hougaard** [comment]
Well, it should give you a better compile error....

**Comment by hougaard** [comment]
Next version will give a proper error.
