### ISSUE TITLE
unable to run another codeunit ?

### ISSUE THREAD

**Issue by dcilindac** [hougaard/ToolBox-Issues#8]
![image](https://user-images.githubusercontent.com/122482075/211898737-b43fc7d9-2197-4bdb-a8ae-1df2e73d1d05.png)
I'm trying to call another codeunit but doesn't seem like it recognize it.

ps. I also tried this but it didn't work as well > Codeunit.Run(Codeunit::"CRM Integration Management");

**Comment by hougaard** [comment]
There's no support for codeunits as variables ... The platform is lagging support for that.

But you can do:

Codeunit.run(5330);

To be able to use CRM tables.

**Comment by hougaard** [comment]
Version 1.0.0.181 supports guid variable types.
