### ISSUE TITLE
Type mismatch 

### ISSUE THREAD

**Issue by dcilindac** [hougaard/ToolBox-Issues#9]
When trying to update guid , I get this error : Runtime Error Type mismatch (Time vs Text)

![image](https://user-images.githubusercontent.com/122482075/212191447-cab40903-a51f-4f8e-a2b3-6384d58cde3d.png)

**Comment by hougaard** [comment]
Hmm.... try without validate (just use :=)

**Comment by dcilindac** [comment]
still mismatch but this time it's (Guid vs Text)
![image](https://user-images.githubusercontent.com/122482075/212193114-88928a74-88d8-4c00-b1ac-245a1ec5672d.png)

**Comment by hougaard** [comment]
Let me try....

**Comment by hougaard** [comment]
I see it, hang on and check for an updated ToolBox in an hour or so
